[build]
command = "npm run build"
publish = "build"  # ให้มั่นใจว่า `build` โฟลเดอร์มีไฟล์ output จากการ build

[[redirects]]
from = "/api/*"
to = "https://gardano-production.up.railway.app/api/:splat"
status = 200
force = true
headers = { "Access-Control-Allow-Origin" = "*" }