[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "https://gardano-production.up.railway.app/api/:splat"
  status = 200
  force = true
  headers = { "Access-Control-Allow-Origin" = "*" }